### ISSUE TITLE
[ACTUAL-SERVER] Loading WebApp results in Exception

### ISSUE THREAD

**Issue by LackesLab** [Kippenhof/docker-templates#13]
Hi there,
first, I want to thank you for the docker image. I set up the Actual Server via your Docker image.
When reloading the "main page" to start the syncing process, the server logs output the following:

I mount an appdata directory into the container `/mnt/user/appdata/ActualServer -> /data` and set the `ACTUAL_USER_FILES` variable to /data.

Unfortunately, the container logs display the following message. Seems there are some issies with "budget directory". I have no glue what is meant by this. 

```
[Exception] Error: budget directory does not exist
    at loadBudget (/app/node_modules/@actual-app/api/app/bundle.api.js:57516:83)
    at async module.exports../packages/loot-core/src/server/main.js.handlers.load-budget (/app/node_modules/@actual-app/api/app/bundle.api.js:57251:13)
error SELECT timestamp, dataset, row, column, value FROM messages_crdt WHERE timestamp > ?
Rejection: TypeError: Cannot read properties of undefined (reading 'prepare')
    at Module.runQuery (/app/node_modules/@actual-app/api/app/bundle.api.js:45806:41)
    at Module.runQuery (/app/node_modules/@actual-app/api/app/bundle.api.js:54349:82)
    at getMessagesSince (/app/node_modules/@actual-app/api/app/bundle.api.js:61540:54)
    at Object.syncAndReceiveMessages (/app/node_modules/@actual-app/api/app/bundle.api.js:61543:29)
    at syncAPI (/app/sync-full.js:30:37)
Rejection: TypeError: Cannot read properties of null (reading 'merkle')
    at syncAPI (/app/sync-full.js:33:47)
```

Best regards

**Comment by hofq** [comment]
Unfortunately that is an issue with the Official Build. I Tried merging the Pull-Request in my Local Build, but it don't seem to be ready.
You can see the Status on the Issue here: https://github.com/actualbudget/actual-server/pull/52

**Comment by hofq** [comment]
Hey there,

the Pull Request is merged and the Issue should be fixed. Could you check if that worked out for you?

**Comment by hofq** [comment]
Hi, since this issue should be fixed (see https://github.com/actualbudget/actual-server/pull/52) i will close this issue. 
Please reopen if you still have any Errors related to the Synchronization.
